### PR TITLE
PIP-381 Implement functionality of bump version

### PR DESCRIPTION
**Pull request by kikeda-falcons**
This PR introduces the core functionality of generating the next version based on a specified tag format and an optional version.json file.

Please refer to the README.md file for detailed instructions on how to use this functionality.

Any feedback or suggestions would be appreciated! Thanks!

### CODE REVIEW

**Review by triley13 — COMMENTED** [review]
Nice work! Out of curiosity, why are the dist files needed? Usually they aren't to be included in the src code, but built when deployed.

**Comment by kikeda-falcons** [comment]
> Nice work! Out of curiosity, why are the dist files needed? Usually they aren't to be included in the src code, but built when deployed.

Great question, sir! I thought the same thing in the beginning of the development, but I found out that without dist files, I would have to check in `node_modules` directory which can cause potential problems later and visibly noisy in the repository. So I thought I could use a tool called @vercel/ncc to compile my code and modules into one file used for distribution as following the official guidance how to [create a Javascript action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action). Do you usually check in `node_modules` and let CI workflow to build and distribute for your Javascript project? :) I would love to learn your development workflow with Javascript.

**Comment by triley13** [comment]
> > Nice work! Out of curiosity, why are the dist files needed? Usually they aren't to be included in the src code, but built when deployed.
> 
> Great question, sir! I thought the same thing in the beginning of the development, but I found out that without dist files, I would have to check in `node_modules` directory which can cause potential problems later and visibly noisy in the repository. So I thought I could use a tool called @vercel/ncc to compile my code and modules into one file used for distribution as following the official guidance how to [create a Javascript action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action). Do you usually check in `node_modules` and let CI workflow to build and distribute for your Javascript project? :) I would love to learn your development workflow with Javascript.

Yeah, normally you gitignore node_modules and when you deploy to the cloud, depending on your cloud provider, you either run build locally and deploy, or you run build and deploy on the VM server directly. But, I read the documentation, and it says to do so; so lgtm!

**Review by triley13 — COMMENTED** [review]
Nice work!

**Comment by kikeda-falcons** [comment]
@triley13 , thank you, sir!

**Comment by kikeda-falcons** [comment]
> Nice work!

@triley13 , thank you, sir!

**Pull request merged**
